spring:
  redis:
    host: 127.0.0.1
    port: 6379

kakao:
  authUrl: https://kauth.kakao.com/oauth/authorize?
  restapiKey: client_id=여기에 REST API KEY 입력&
  redirectUrl:  redirect_uri=http://localhost:8080/callback


