server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: ${REDIS_SERVICE}
    port: 6379

jwt:
  secretKey: ENC(FFqIhuVHP55GbmEItS8qE6yuBnqu6uy8pH7iGmebJW9NB0AEtYPesSJndj1Mqb2H2CasgMESlggdCQDnY98j8US2kEbSVEiqip3xIbBrRlPNVbzzIb4wLrgfHxZks9gdmGCaqttRLw8=)

jasypt:
  encryptor:
    enabled: true

kakao:
  token-url: https://kauth.kakao.com/oauth/token
  user-api-url: https://kapi.kakao.com/v2/user/me
  rest-api-key: ${KAKAO_CLIENT_ID}
  redirect-url:  ${REDIRECT_URL}login/kakao
  client-secret: ${KAKAO_CLIENT_SECRET}

google:
  token-url: https://oauth2.googleapis.com/token
  user-api-url: https://www.googleapis.com/oauth2/v3/userinfo
  redirect-url: ${REDIRECT_URL}login/google
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

cloud:
  aws:
    s3:
      bucket: kakaotechcampust-step3-nemobucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAVBQDJ37FAVI2YLP2
      secretKey: cmAkLF5DlpMomdatXcHWjt8EKMvxEhkfvow6D/iC
      
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils : error
      example:
        team2_be:
          auth: DEBUG
